name: Build

on: push

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Upgrade openssl (Mac only)
              if: ${{ matrix.os == 'macos-latest'}}
              run: |
                  ls /usr/local/opt/openssl/lib
                  echo "---"
                  ls /usr/local/opt/openssl@1.1/lib
                  cp -r /usr/local/opt/openssl@1.1 /usr/local/opt/openssl
                  echo "------"
                  ls /usr/local/opt/openssl/lib
                  echo "---"
                  ls /usr/local/opt/openssl@1.1/lib

            - name: Install esy
              run: npm i -g esy

            - name: Update esy resolution (Windows only)
              if: ${{ matrix.os == 'windows-latest'}}
              run: node .github/scripts/esy.json.js

            - name: Try to restore cache
              uses: actions/cache@v1
              with:
                  path: ~/.esy/source
                  key: source-${{ hashFiles('**/index.json') }}

            - name: Esy install
              run: esy install

            - name: Print esy cache
              id: print_esy_cache
              run: node .github/workflows/print_esy_cache.js

            - name: Try to restore build cache
              id: deps-cache-macos
              uses: actions/cache@v1
              with:
                  path: ${{ steps.print_esy_cache.outputs.esy_cache }}
                  key: build-${{ matrix.os }}-${{ hashFiles('**/index.json') }}
                  restore-keys: build-${{ matrix.os }}-

            - name: Esy build
              run: |
                  esy build
                  # Cleanup build cache in case dependencies have changed
                  esy cleanup .

            - name: Esy Release
              run: |
                  esy release
                  cd _release
                  node esyInstallRelease.js
                  cd ..

            - name: Copy bin to the root of _release
              if: ${{ matrix.os != 'windows-latest'}}
              run: cp _release/3/i/$(ls _release/3/i)/bin/ppx-figma _release/ppx

            - name: Copy bin to the root of _release (Windows version)
              if: ${{ matrix.os == 'windows-latest'}}
              run: cp _release/3/i/$(ls _release/3/i)/bin/ppx-figma.exe _release/ppx

            - name: Save build bin
              uses: actions/upload-artifact@v1
              with:
                  name: bin-${{ matrix.os }}
                  path: _release/ppx
