name: Build

on: push

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org

            - name: Install esy
              run: npm i -g esy

            # - name: Update esy resolution (Windows only)
            #   if: ${{ matrix.os == 'windows-latest'}}
            #   run: node .github/scripts/esy.json.js

            - name: Try to restore cache
              uses: actions/cache@v1
              with:
                  path: ~/.esy/source
                  key: source-${{ hashFiles('**/index.json') }}

            - name: Esy install
              run: esy install

            - name: Print esy cache
              id: print_esy_cache
              run: node .github/workflows/print_esy_cache.js

            - name: Try to restore build cache
              id: deps-cache-macos
              uses: actions/cache@v1
              with:
                  path: ${{ steps.print_esy_cache.outputs.esy_cache }}
                  key: build-${{ matrix.os }}-${{ hashFiles('**/index.json') }}
                  restore-keys: build-${{ matrix.os }}-

            - name: Esy build
              run: |
                  esy build
                  # Cleanup build cache in case dependencies have changed
                  # esy cleanup .

            - name: Logging
              run: |
                  ls .
                  ls _esy
                  ls _esy/default
                  ls -esy/default/build/default

            - name: Save build bin (Windows edition)
              uses: actions/upload-artifact@v1
              if: ${{ matrix.os == 'windows-latest'}}
              with:
                  name: bin-${{ matrix.os }}
                  path: _esy/default/build/default/bin/PpxFigma.exe

            - name: Save build bin
              uses: actions/upload-artifact@v1
              if: ${{ matrix.os != 'windows-latest'}}
              with:
                  name: bin-${{ matrix.os }}
                  path: _build/default/bin/PpxFigma.exe
